stages:
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: dannyst@zoho.eu
    notifier: c-6plhj:n-tgk4g
  condition:
  - Success
  - Changed
  - Failed
